export default function() {
  return {
    list: [
      {
        id: 1122,
        gender: "male",
        first_name: "Hossein",
        last_name: "Heidari",
        photo: "1122_user.JPG",
        height: 180,
        username: "hossein",
        bio: "A passionate freestylist.",
        created_at: "1598032502715",
        updated_at: "",
        sport: "Basketball",
        photos: ["1122_user_pic_1", "1122_user_pic_2"],
        friends: [1133, 1144, 1155, 1166],
        scopes: ["c", "a", "b"],
        verified: true
      },
      {
        id: 1133,
        gender: "female",
        first_name: "Parnia",
        last_name: "Esna Ashari",
        photo: "1122_user.JPG",
        height: 175,
        username: "parnia",
        bio: "Only God can get passed me.",
        created_at: "1598032502815",
        updated_at: "",
        sport: "Basketball",
        photos: [""],
        friends: [1122, 1144, 1155, 1166],
        scopes: ["c", "a", "b"],
        verified: true
      },
      {
        id: 1144,
        gender: "male",
        first_name: "Mehran",
        last_name: "Shabani",
        photo: "1122_user.JPG",
        height: 190,
        username: "mehran",
        bio: "Don't waste my time playing nonsense.",
        created_at: "1598032502915",
        updated_at: "",
        sport: "Basketball",
        photos: ["1122_user_pic_1", "1122_user_pic_2"],
        friends: [1122, 1133, 1155, 1166],
        scopes: ["c", "a", "b"],
        verified: true
      },
      {
        id: 1177,
        gender: "male",
        first_name: "Mammad",
        last_name: "Sobhani",
        photo: "1122_user.JPG",
        height: 183,
        username: "mammad",
        bio: "Not tryina prove no nothing to nobody.",
        created_at: "1598032503715",
        updated_at: "",
        sport: "Basketball",
        photos: ["1122_user_pic_1", "1122_user_pic_2"],
        friends: [1122, 1133, 1155, 1166],
        scopes: ["c", "a", "b"],
        verified: ""
      },
      {
        id: 1188,
        gender: "female",
        first_name: "Masoome",
        last_name: "Esmaili",
        photo: "1122_user.JPG",
        height: 180,
        username: "massoome",
        bio: "I'll chase you down if you bullshit.",
        created_at: "1598032502819",
        updated_at: "",
        sport: "Basketball",
        photos: ["1122_user_pic_1", "1122_user_pic_2"],
        friends: [1122, 1133, 1155, 1166],
        scopes: ["c", "a", "b"],
        verified: true
      }
    ]
  };
}
